package no.nav.helse.person

enum class TilstandType {
    START,
    MOTTATT_NY_SØKNAD,
    AVVENTER_SENDT_SØKNAD,
    AVVENTER_TIDLIGERE_PERIODE_ELLER_INNTEKTSMELDING,
    AVVENTER_TIDLIGERE_PERIODE,
    UNDERSØKER_HISTORIKK,
    AVVENTER_INNTEKTSMELDING,
    AVVENTER_VILKÅRSPRØVING,
    AVVENTER_HISTORIKK,
    AVVENTER_GODKJENNING,
    TIL_UTBETALING,
    TIL_INFOTRYGD
}
