package no.nav.helse.person

enum class TilstandType {
    START,
    MOTTATT_NY_SØKNAD,
    AVVENTER_SENDT_SØKNAD,
    UNDERSØKER_HISTORIKK,
    AVVENTER_INNTEKTSMELDING,
    AVVENTER_VILKÅRSPRØVING,
    AVVENTER_HISTORIKK,
    AVVENTER_GODKJENNING,
    TIL_UTBETALING,
    TIL_INFOTRYGD
}

enum class TilstandTypeGammelOgNy {
    START,
    MOTTATT_NY_SØKNAD,
    AVVENTER_SENDT_SØKNAD,
    UNDERSØKER_HISTORIKK,
    AVVENTER_INNTEKTSMELDING,
    AVVENTER_VILKÅRSPRØVING,
    AVVENTER_HISTORIKK,
    AVVENTER_GODKJENNING,
    TIL_UTBETALING,
    TIL_INFOTRYGD,
    MOTTATT_SENDT_SØKNAD,
    MOTTATT_INNTEKTSMELDING,
    BEREGN_UTBETALING,
    TIL_GODKJENNING,
    VILKÅRSPRØVING

}
