package no.nav.helse.person

enum class TilstandType {
    START,
    MOTTATT_SYKMELDING,
    AVVENTER_SØKNAD,
    AVVENTER_TIDLIGERE_PERIODE_ELLER_INNTEKTSMELDING,
    AVVENTER_TIDLIGERE_PERIODE,
    UNDERSØKER_HISTORIKK,
    AVVENTER_INNTEKTSMELDING,
    AVVENTER_VILKÅRSPRØVING,
    AVVENTER_HISTORIKK,
    AVVENTER_GODKJENNING,
    TIL_UTBETALING,
    TIL_INFOTRYGD,
    UTBETALT
}
