package no.nav.helse.spleis.serde

internal enum class Inntektsopplysningskilde {
    SKATT_SAMMENLIGNINGSGRUNNLAG, SKATT_SYKEPENGEGRUNNLAG, INFOTRYGD, INNTEKTSMELDING, SAKSBEHANDLER, IKKE_RAPPORTERT, SKJØNNSMESSIG_FASTSATT
}

