version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "⬆️ "
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      exclude:
        - "navikt/sykepenger-github-workflows*"

  # Maintain dependencies for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    commit-message:
      prefix: "⬆️ "
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      exclude:
        - "no.nav.sykepenger.*"
        - "com.github.navikt.tbd-libs:*"
