apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spleis-api
  namespace: tbd
  labels:
    team: tbd
    db: spleis # trengs bare ifm. 'spleis-db-policy'
spec:
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    initialDelay: 5
    periodSeconds: 1
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: spesialist
        - application: spanner
        - application: sporing
        - application: sp-vilkarsproving
        - application: speil
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: spekemat
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
