ALTER TABLE melding ADD COLUMN melding_id VARCHAR(40) NOT NULL DEFAULT '';
ALTER TABLE melding ADD COLUMN melding_type VARCHAR(40) NOT NULL DEFAULT 'UKJENT';

ALTER TABLE melding ALTER COLUMN melding_id DROP DEFAULT;
ALTER TABLE melding ALTER COLUMN melding_type DROP DEFAULT;
