ALTER TABLE person ALTER COLUMN fnr TYPE BIGINT USING(fnr::BIGINT);
ALTER TABLE person ALTER COLUMN aktor_id TYPE BIGINT USING(aktor_id::BIGINT);
ALTER TABLE melding ALTER COLUMN fnr TYPE BIGINT USING(fnr::BIGINT);
