package no.nav.helse.serde.mapping

enum class JsonDagType {
    ARBEIDSDAG,
    ARBEIDSGIVERDAG,
    ARBEIDSGIVER_HELGEDAG,
    FERIEDAG,
    FRISK_HELGEDAG,
    FORELDET_SYKEDAG,
    PERMISJONSDAG,
    PROBLEMDAG,
    STUDIEDAG,
    SYKEDAG,
    SYK_HELGEDAG,
    UTENLANDSDAG,
    UKJENT_DAG,
}
