package no.nav.helse.sak

enum class TilstandType {
    START,
    MOTTATT_NY_SØKNAD,
    MOTTATT_SENDT_SØKNAD,
    MOTTATT_INNTEKTSMELDING,
    BEREGN_UTBETALING,
    TIL_GODKJENNING,
    TIL_UTBETALING,
    TIL_INFOTRYGD
}
