package no.nav.helse.sak

enum class TilstandType {
    START,
    NY_SØKNAD_MOTTATT,
    SENDT_SØKNAD_MOTTATT,
    INNTEKTSMELDING_MOTTATT,
    KOMPLETT_SYKDOMSTIDSLINJE,
    TIL_GODKJENNING,
    TIL_UTBETALING,
    TIL_INFOTRYGD
}
