---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: subsumsjon.v1
  namespace: tbd
  labels:
    team: tbd
spec:
  pool: nav-dev
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 6
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 24  # -1 means unlimited
  acl:
    - team: tbd
      application: helse-spleis
      access: write
    - team: tbd
      application: spre-subsumsjon
      access: read
