---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
    name: rapid.v1
    namespace: tbd
    labels:
        team: tbd
spec:
    pool: nav-dev
    config:  # optional; all fields are optional too; defaults shown
        cleanupPolicy: delete  # delete, compact
        minimumInSyncReplicas: 1
        partitions: 6
        replication: 3  # see min/max requirements
        retentionBytes: -1  # -1 means unlimited
        retentionHours: 168  # -1 means unlimited
    acl:
        - team: tbd
          application: dataprodukt-forstegangsbehandling
          access: readwrite
        - team: tbd
          application: dataprodukt-iverksettelser
          access: readwrite
        - team: tbd
          application: dataprodukt-annulleringer
          access: readwrite
        - team: tbd
          application: spre-subsumsjon
          access: readwrite
        - team: tbd
          application: spennende
          access: readwrite
        - team: tbd
          application: behovsakkumulator
          access: readwrite
        - team: tbd
          application: sporing
          access: readwrite
        - team: tbd
          application: spaghet
          access: readwrite
        - team: tbd
          application: spammer
          access: readwrite
        - team: tbd
          application: spare
          access: readwrite
        - team: tbd
          application: helse-sparker-feriepenger
          access: readwrite
        - team: tbd
          application: sparker-alt
          access: write
        - team: tbd
          application: sparkel-aareg
          access: readwrite
        - team: tbd
          application: sparkel-arena
          access: readwrite
        - team: tbd
          application: sparkel-dkif
          access: readwrite
        - team: tbd
          application: sparkel-gosys
          access: readwrite
        - team: tbd
          application: sparkel-inntekt
          access: readwrite
        - team: tbd
          application: sparkel-institusjonsopphold
          access: readwrite
        - team: tbd
          application: sparkel-medlemskap
          access: readwrite
        - team: tbd
          application: sparkel-norg
          access: readwrite
        - team: tbd
          application: sparkel-personinfo
          access: readwrite
        - team: tbd
          application: sparkel-pleiepenger
          access: readwrite
        - team: tbd
          application: sparkel-sykepengeperioder
          access: readwrite
        - team: tbd
          application: sparkel-vilkarsproving
          access: readwrite
        - team: tbd
          application: spedisjon
          access: readwrite
        - team: tbd
          application: speider
          access: readwrite
        - team: tbd
          application: speil
          access: readwrite
        - team: tbd
          application: speil-redis
          access: readwrite
        - team: tbd
          application: spenn
          access: readwrite
        - team: tbd
          application: spenn-simulering
          access: readwrite
        - team: tbd
          application: spenn-avstemming
          access: readwrite
        - team: tbd
          application: spenn-opprydding-dev
          access: readwrite
        - team: tbd
          application: spesialist
          access: readwrite
        - team: tbd
          application: spesialist-migrering
          access: readwrite
        - team: tbd
          application: spotter
          access: readwrite
        - team: tbd
          application: spetakkel
          access: readwrite
        - team: tbd
          application: spill-av
          access: readwrite
        - team: tbd
          application: spoler
          access: readwrite
        - team: tbd
          application: helse-spleis
          access: readwrite
        - team: tbd
          application: spleis-api
          access: readwrite
        - team: tbd
          application: spleis-avstemming
          access: readwrite
        - team: tbd
          application: spock
          access: readwrite
        - team: tbd
          application: spokelse
          access: readwrite
        - team: tbd
          application: sporbar
          access: readwrite
        - team: tbd
          application: spre-arbeidsgiver
          access: readwrite
        - team: tbd
          application: spre-gosys
          access: readwrite
        - team: tbd
          application: spre-gosys-pdf
          access: readwrite
        - team: tbd
          application: spre-oppgaver
          access: readwrite
        - team: tbd
          application: spre-saksbehandlingsstatistikk
          access: readwrite
        - team: tbd
          application: spre-stonadsstatistikk
          access: readwrite
        - team: tbd
          application: sputnik
          access: readwrite
        - team: tbd
          application: sparkel-sputnik
          access: readwrite
        - team: tbd
          application: vedtaksfeed
          access: readwrite
        - team: risk
          application: sigmund
          access: readwrite
        - team: risk
          application: helserisk-treskeverk
          access: readwrite
        - team: tbd
          application: sparkel-sykepengeperioder-mock
          access: readwrite
        - team: tbd
          application: risk-mock
          access: readwrite
        - team: tbd
          application: spleis-testdata
          access: readwrite
        - team: tbd
          application: spleis-opprydding-dev
          access: readwrite
        - team: tbd
          application: spesialist-opprydding-dev
          access: readwrite
        - team: tbd
          application: sparkel-medlemskap-mock
          access: readwrite
        - team: tbd
          application: sparkel-oppgave-endret
          access: readwrite
        - team: tbd
          application: sparkel-identer
          access: readwrite
        - team: tbd
          application: sparkel-skjermet-endret
          access: readwrite
        - team: tbd
          application: sparkel-arbeidsgiver
          access: readwrite
        - team: tbd
          application: sportsrevyen
          access: readwrite
        - team: tbd
          application: sparsom
          access: readwrite
        - team: tbd
          application: sparsom-opprydding
          access: readwrite
        - team: tbd
          application: speaker-kafka
          access: readwrite
        - team: tbd
          application: sondre-halvorsen
          access: read
        - team: flex
          application: sykepengesoknad-sak-status-metrikk
          access: read
