apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spleis-api
  namespace: tbd
  labels:
    team: tbd
    db: spleis # trengs bare ifm. 'spleis-db-policy'
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spleis-api.intern.dev.nav.no
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    initialDelay: 5
    periodSeconds: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 70
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - 'NAVident'
        groups:
          - id: 'cda797bb-ac3b-4440-b661-2cd5eb3edba0' # 0000-CA-Speil-Saksbehandler
          - id: '216b7219-3906-43c5-8e22-03fb74133b42' # 0000-CA-Speil_Lesetilgang
  accessPolicy:
    inbound:
      rules:
        - application: spesialist
        - application: spanner
        - application: sporing
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: spekemat
        - application: speed-api-dev-proxy
  filesFrom:
    - secret: google-sql-helse-spleis-spleis-spleis-api-cf4f5c2c
      mountPath: /var/run/secrets/spleis_sql
  env:
    - name: DATABASE_INSTANCE
      value: "helse-spleis"
    - name: SPEKEMAT_SCOPE
      value: "api://dev-gcp.tbd.spekemat/.default"
    - name: SPEED_API_URL
      value: http://speed-api-dev-proxy
    - name: TOKEN_ENDPOINT_ENV_KEY
      value: SPEED_API_DEV_PROXY_TOKEN_ENDPOINT
    - name: SPEED_API_DEV_PROXY_TOKEN_ENDPOINT
      value: http://speed-api-dev-proxy/token
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
