package no.nav.helse.serde.mapping

enum class JsonDagType {
    ARBEIDSDAG_INNTEKTSMELDING,
    ARBEIDSDAG_SØKNAD,
    EGENMELDINGSDAG_INNTEKTSMELDING,
    EGENMELDINGSDAG_SØKNAD,
    FERIEDAG_INNTEKTSMELDING,
    FERIEDAG_SØKNAD,
    FRISK_HELGEDAG_INNTEKTSMELDING,
    FRISK_HELGEDAG_SØKNAD,
    IMPLISITT_DAG,
    FORELDET_SYKEDAG,
    PERMISJONSDAG_SØKNAD,
    PERMISJONSDAG_AAREG,
    STUDIEDAG,
    SYKEDAG_SYKMELDING,
    SYKEDAG_SØKNAD,
    SYK_HELGEDAG_SYKMELDING,
    SYK_HELGEDAG_SØKNAD,
    UBESTEMTDAG,
    UTENLANDSDAG
}

enum class NyJsonDagType {
    ARBEIDSDAG,
    ARBEIDSGIVERDAG,
    ARBEIDSGIVER_HELGEDAG,
    FERIEDAG,
    FRISK_HELGEDAG,
    FORELDET_SYKEDAG,
    PERMISJONSDAG,
    PROBLEMDAG,
    STUDIEDAG,
    SYKEDAG,
    SYK_HELGEDAG,
    UTENLANDSDAG,
    UKJENT_DAG
}

enum class NySpeilJsonDagType {
    ARBEIDSDAG,
    ARBEIDSGIVERDAG,
    FERIEDAG,
    FRISK_HELGEDAG,
    KUN_ARBEIDSGIVER_SYKEDAG,
    PERMISJONSDAG,
    STUDIEDAG,
    SYKEDAG,
    SYK_HELGEDAG,
    UBESTEMTDAG,
    UTENLANDSDAG
}
