package no.nav.helse.serde.mapping

enum class JsonDagType {
    ARBEIDSDAG_INNTEKTSMELDING,
    ARBEIDSDAG_SØKNAD,
    EGENMELDINGSDAG_INNTEKTSMELDING,
    EGENMELDINGSDAG_SØKNAD,
    FERIEDAG_INNTEKTSMELDING,
    FERIEDAG_SØKNAD,
    FRISK_HELGEDAG_INNTEKTSMELDING,
    FRISK_HELGEDAG_SØKNAD,
    IMPLISITT_DAG,
    KUN_ARBEIDSGIVER_SYKEDAG,
    PERMISJONSDAG_SØKNAD,
    PERMISJONSDAG_AAREG,
    STUDIEDAG,
    SYKEDAG_SYKMELDING,
    SYKEDAG_SØKNAD,
    SYK_HELGEDAG_SYKMELDING,
    SYK_HELGEDAG_SØKNAD,
    UBESTEMTDAG,
    UTENLANDSDAG
}
