apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sp-vilkarsproving
  namespace: tbd
  labels:
    team: tbd
spec:
  port: 8080
  startup:
    path: isready
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 9
  liveness:
    path: isalive
  readiness:
    path: isready
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
        - id: team_logs
  replicas:
    min: 1
    max: 2
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sp-vilkarsproving-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: spleis-api
