package no.nav.helse.person.tilstandsmaskin

enum class TilstandType {
    START,
    AVVENTER_INFOTRYGDHISTORIKK,
    AVVENTER_INNTEKTSMELDING,
    AVVENTER_BLOKKERENDE_PERIODE,
    AVVENTER_A_ORDNINGEN,
    AVVENTER_VILKÅRSPRØVING,
    AVVENTER_HISTORIKK,
    AVVENTER_SIMULERING,
    AVVENTER_GODKJENNING,

    AVVENTER_REVURDERING,
    AVVENTER_HISTORIKK_REVURDERING,
    AVVENTER_VILKÅRSPRØVING_REVURDERING,
    AVVENTER_GODKJENNING_REVURDERING,
    AVVENTER_SIMULERING_REVURDERING,
    REVURDERING_FEILET,

    AVVENTER_ANNULLERING,

    TIL_UTBETALING,
    TIL_ANNULLERING,
    TIL_INFOTRYGD,
    AVSLUTTET,
    AVSLUTTET_UTEN_UTBETALING,

    SELVSTENDIG_START,
    SELVSTENDIG_AVVENTER_INFOTRYGDHISTORIKK,
    SELVSTENDIG_AVVENTER_BLOKKERENDE_PERIODE,
    SELVSTENDIG_AVVENTER_VILKÅRSPRØVING,
    SELVSTENDIG_AVVENTER_HISTORIKK,
    SELVSTENDIG_AVVENTER_SIMULERING,
    SELVSTENDIG_AVVENTER_GODKJENNING,

    SELVSTENDIG_TIL_UTBETALING,
    SELVSTENDIG_TIL_INFOTRYGD,
    SELVSTENDIG_AVSLUTTET,
}
