package no.nav.helse.person.tilstandsmaskin

enum class TilstandType {
    START,

    AVVENTER_INFOTRYGDHISTORIKK,
    AVVENTER_INNTEKTSMELDING,
    AVVENTER_AVSLUTTET_UTEN_UTBETALING,
    AVVENTER_BLOKKERENDE_PERIODE,
    AVVENTER_SØKNAD_FOR_OVERLAPPENDE_PERIODE,
    AVVENTER_INNTEKTSOPPLYSNINGER_FOR_ANNEN_ARBEIDSGIVER,
    AVVENTER_REFUSJONSOPPLYSNINGER_ANNEN_PERIODE,
    AVVENTER_A_ORDNINGEN,
    AVVENTER_VILKÅRSPRØVING,
    AVVENTER_HISTORIKK,
    AVVENTER_SIMULERING,
    AVVENTER_GODKJENNING,

    AVVENTER_REVURDERING,
    AVVENTER_REVURDERING_TIL_UTBETALING,
    AVVENTER_HISTORIKK_REVURDERING,
    AVVENTER_VILKÅRSPRØVING_REVURDERING,
    AVVENTER_GODKJENNING_REVURDERING,
    AVVENTER_SIMULERING_REVURDERING,

    AVVENTER_ANNULLERING,
    AVVENTER_ANNULLERING_TIL_UTBETALING,

    TIL_UTBETALING,
    TIL_ANNULLERING,
    TIL_INFOTRYGD,
    AVSLUTTET,
    AVSLUTTET_UTEN_UTBETALING,

    FRILANS_START,
    FRILANS_AVVENTER_INFOTRYGDHISTORIKK,
    FRILANS_AVVENTER_BLOKKERENDE_PERIODE,

    ARBEIDSLEDIG_START,
    ARBEIDSLEDIG_AVVENTER_INFOTRYGDHISTORIKK,
    ARBEIDSLEDIG_AVVENTER_BLOKKERENDE_PERIODE,

    SELVSTENDIG_START,
    SELVSTENDIG_AVVENTER_INFOTRYGDHISTORIKK,
    SELVSTENDIG_AVVENTER_BLOKKERENDE_PERIODE,
    SELVSTENDIG_AVVENTER_VILKÅRSPRØVING,
    SELVSTENDIG_AVVENTER_HISTORIKK,
    SELVSTENDIG_AVVENTER_SIMULERING,
    SELVSTENDIG_AVVENTER_GODKJENNING,

    SELVSTENDIG_AVVENTER_REVURDERING,
    SELVSTENDIG_AVVENTER_HISTORIKK_REVURDERING,
    SELVSTENDIG_AVVENTER_VILKÅRSPRØVING_REVURDERING,
    SELVSTENDIG_AVVENTER_GODKJENNING_REVURDERING,
    SELVSTENDIG_AVVENTER_SIMULERING_REVURDERING,
    SELVSTENDIG_AVVENTER_TIL_UTBETALING_REVURDERING,

    SELVSTENDIG_TIL_UTBETALING,
    SELVSTENDIG_AVSLUTTET,
}
